MVLM_DATASET=docile_5k
TOKEN_CLASSIF_DATASET=docile
# FULL_PIPELINE_BASE_PATH=
SUBSET_INDEX_PATH=data/docile/subsets_index/5k.json
HOME_DIR=$SCRATCH/DeepInsuranceDocs  # To adjust

MODEL_NAME=layoulm-base-uncased
PRETRAINED_MODEL=null
PREPROCESS_NORMALIZE_TXT=true
PREPROCESS_TAG_SCHEME=BIO

EPOCH_NUM=5
BATCH_SIZE=10
LEARNING_RATE=5e-5
GRADIENT_ACCUMULATION_STEPS=0
MVLM_CONFIG_PATH=experiments/from_scratch_mvlm_docile_5k.json

# Run MVLM on docile_5k without pretraining
bash scripts/run_pretraining.sh\
    MVLM_DATASET=$MVLM_DATASET\
    TOKEN_CLASSIF_DATASET=$TOKEN_CLASSIF_DATASET\
    SUBSET_INDEX_PATH=$SUBSET_INDEX_PATH\
    HOME_DIR=$HOME_DIR\
    MODEL_NAME=$MODEL_NAME\
    PRETRAINED_MODEL=$PRETRAINED_MODEL\
    PREPROCESS_NORMALIZE_TXT=$PREPROCESS_NORMALIZE_TXT\
    PREPROCESS_TAG_SCHEME=$PREPROCESS_TAG_SCHEME\
    EPOCH_NUM=$EPOCH_NUM\
    BATCH_SIZE=$BATCH_SIZE\
    LEARNING_RATE=$LEARNING_RATE\
    GRADIENT_ACCUMULATION_STEPS=$GRADIENT_ACCUMULATION_STEPS\
    MVLM_CONFIG_PATH=$MVLM_CONFIG_PATH

# Run Token Classif on docile with model pretrained on docile_5k
